server:
  port: 18445

spring:
  datasource:
    #    username: musen
    #    password: NzydDAts8JGNZ6wz
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/empty_classroom?ServerTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
